trigger:

     - main



pool:

      vmImage: 'ubuntu-latest'



steps:

     - task: UsePythonVersion@0

        inputs:

             versionSpec: '3.x'



     - script: pip install -r requirements.txt

   displayName: 'Install dependencies'



 - task: AzureWebApp@1

   inputs:

         azureSubscription: 'Microsoft.Web'

         appType: 'webAppLinux'

         appName: 'MenchCima'

         package: '.'

